import { z } from 'zod'

import { EventIdSchema } from '../ids'
import { EVENT_TYPES, EventSeqSchema, ProcessedAtSchema } from './common'

/**
 * Span events: observability markers that wrap a model request.
 *
 * Every model request is bracketed by a `span.model_request_start` and a
 * `span.model_request_end` carrying its token usage, so a client can time a request and add
 * up a turn's cost from the log alone. The end event is always written, even when the request
 * was aborted by an interrupt or its span was closed by a recovering brain.
 */

/**
 * Token counts for one model request. Matches Anthropic's `BetaManagedAgentsSpanModelUsage`
 * without its optional `speed` field.
 */
export const ModelUsageSchema = z.object({
  /** Tokens used to create prompt cache in this request. */
  cache_creation_input_tokens: z.number().int().nonnegative(),
  /** Tokens read from prompt cache in this request. */
  cache_read_input_tokens: z.number().int().nonnegative(),
  /** Input tokens consumed by this request. */
  input_tokens: z.number().int().nonnegative(),
  /** Output tokens generated by this request. */
  output_tokens: z.number().int().nonnegative(),
})

export type ModelUsage = z.infer<typeof ModelUsageSchema>

/**
 * // extension: why a model request ended without a normal reply.
 *
 * Anthropic's `span.model_request_end` only has `is_error`; openharness adds the reason, which
 * the client and the session store need in order to tell three different situations apart:
 *
 * - `interrupted` — a `user.interrupt` cut the request short. The partial text is stored as
 *   an `agent.message` and the turn still ends with `end_turn`.
 * - `brain_lost` — the brain instance died mid-request. A recovering brain closes the orphaned
 *   span with this, then re-runs the turn.
 * - `model_error` — the model request failed (the `session.error` that follows carries the
 *   detail).
 */
export const SpanErrorTypeSchema = z.enum(['interrupted', 'brain_lost', 'model_error'])

export type SpanErrorType = z.infer<typeof SpanErrorTypeSchema>

/** The `error` of a `span.model_request_end` event. */
export const SpanErrorSchema = z.object({
  type: SpanErrorTypeSchema,
  message: z.string().optional(),
})

export type SpanError = z.infer<typeof SpanErrorSchema>

/** A model request started. */
export const ModelRequestStartEventSchema = z.object({
  id: EventIdSchema,
  type: z.literal(EVENT_TYPES.modelRequestStart),
  seq: EventSeqSchema,
  processed_at: ProcessedAtSchema,
})

export type ModelRequestStartEvent = z.infer<typeof ModelRequestStartEventSchema>

/**
 * A model request finished.
 *
 * `model_request_start_id` points at the matching `span.model_request_start`, which is what
 * lets a brain recovering from a crash find and close the span it inherited.
 */
export const ModelRequestEndEventSchema = z.object({
  id: EventIdSchema,
  type: z.literal(EVENT_TYPES.modelRequestEnd),
  seq: EventSeqSchema,
  processed_at: ProcessedAtSchema,
  /** The `span.model_request_start` this closes. */
  model_request_start_id: EventIdSchema,
  /** Token usage for this request. */
  model_usage: ModelUsageSchema,
  /** Whether the model request resulted in an error. */
  is_error: z.boolean().nullable(),
  /**
   * // extension: why the request failed or was aborted.
   *
   * Written together with `is_error: true`; a request that completed normally has neither.
   * The schema does not enforce that pairing — a consumer that wants the reason should read
   * `error`, and one that only wants a yes/no should read `is_error` — but the server always
   * writes the two consistently.
   */
  error: SpanErrorSchema.optional(),
})

export type ModelRequestEndEvent = z.infer<typeof ModelRequestEndEventSchema>

/** Any stored span event. */
export const SpanEventSchema = z.discriminatedUnion('type', [
  ModelRequestStartEventSchema,
  ModelRequestEndEventSchema,
])

export type SpanEvent = z.infer<typeof SpanEventSchema>
