import { z } from 'zod'

import { EventIdSchema } from '../ids'
import type { DeepReadonly } from '../readonly'
import { EVENT_TYPES, EventSeqSchema, ProcessedAtSchema, SupersedesSchema } from './common'

/**
 * Span events: observability markers that wrap a model request.
 *
 * Every model request is bracketed by a `span.model_request_start` and a
 * `span.model_request_end` carrying its token usage, so a client can time a request and add
 * up a turn's cost from the log alone. The end event is always written, even when the request
 * was aborted by an interrupt or its span was closed by a recovering brain.
 */

/**
 * Token counts for one model request. Matches Anthropic's `BetaManagedAgentsSpanModelUsage`
 * without its optional `speed` field.
 */
export const ModelUsageSchema = z.object({
  /** Tokens used to create prompt cache in this request. */
  cache_creation_input_tokens: z.number().int().nonnegative(),
  /** Tokens read from prompt cache in this request. */
  cache_read_input_tokens: z.number().int().nonnegative(),
  /** Input tokens consumed by this request. */
  input_tokens: z.number().int().nonnegative(),
  /** Output tokens generated by this request. */
  output_tokens: z.number().int().nonnegative(),
})

export type ModelUsage = z.infer<typeof ModelUsageSchema>

/**
 * // extension: why a model request ended without a normal reply.
 *
 * Anthropic's `span.model_request_end` only has `is_error`; openharness adds the reason, which
 * the client and the session store need in order to tell three different situations apart:
 *
 * - `interrupted` — a `user.interrupt` cut the request short. The partial text is stored as
 *   an `agent.message` and the turn still ends with `end_turn`.
 * - `brain_lost` — the brain instance died mid-request. A recovering brain closes the orphaned
 *   span with this, then re-runs the turn.
 * - `model_error` — the model request failed (the `session.error` that follows carries the
 *   detail).
 */
export const SpanErrorTypeSchema = z.enum(['interrupted', 'brain_lost', 'model_error'])

export type SpanErrorType = z.infer<typeof SpanErrorTypeSchema>

/** The `error` of a `span.model_request_end` event. */
export const SpanErrorSchema = z.object({
  type: SpanErrorTypeSchema,
  message: z.string().optional(),
})

export type SpanError = z.infer<typeof SpanErrorSchema>

/**
 * A model request started, and the user events it claims.
 *
 * Since D9 (issue #46) this event is also the *claim*: the request it opens answers exactly
 * the user events its `consumes` lists, so "which user message is still waiting for an answer"
 * is a question a reader answers from the log itself, with no mutable `processed_at` column
 * behind it. A claim is ordinary event data: an event that is already consumed by one span
 * cannot be consumed again, and the store enforces that when the span is appended — atomic and
 * fenced like every other write (phase P2a).
 */
export const ModelRequestStartEventSchema = z.object({
  id: EventIdSchema,
  type: z.literal(EVENT_TYPES.modelRequestStart),
  seq: EventSeqSchema,
  processed_at: ProcessedAtSchema,
  /**
   * // extension: the user events this request claims — the `sevt_` ids of the
   * `user.message` / `user.interrupt` events it folds into the request.
   *
   * Optional for the D9 transition only, so events stored before D9 and writers that have not
   * been ported yet still validate; phase P3 makes the brain set it on every request it
   * appends, and it is then never absent in a log written from scratch. An empty array claims
   * nothing.
   */
  consumes: z.array(EventIdSchema).optional(),
  /**
   * // extension: the model that served this request, a Mastra router string
   * (`provider/model`) — the same spelling as `model.id` on the agent.
   *
   * It is recorded per request rather than read off the agent so that a session which changes
   * models mid-conversation keeps, for every request, the model that actually ran — per-model
   * context budgets and the usage the span end reports are then both attributable. Optional
   * for the D9 transition only, like `consumes` above.
   */
  model: z.string().min(1).optional(),
})

export type ModelRequestStartEvent = z.infer<typeof ModelRequestStartEventSchema>

/** {@link ModelRequestStartEvent}, deep-readonly: the shape a store returns (D9). */
export type ImmutableModelRequestStartEvent = DeepReadonly<ModelRequestStartEvent>

/**
 * A model request finished.
 *
 * `model_request_start_id` points at the matching `span.model_request_start`, which is what
 * lets a brain recovering from a crash find and close the span it inherited.
 */
export const ModelRequestEndEventSchema = z.object({
  id: EventIdSchema,
  type: z.literal(EVENT_TYPES.modelRequestEnd),
  seq: EventSeqSchema,
  processed_at: ProcessedAtSchema,
  /** The `span.model_request_start` this closes. */
  model_request_start_id: EventIdSchema,
  /** Token usage for this request. */
  model_usage: ModelUsageSchema,
  /** Whether the model request resulted in an error. */
  is_error: z.boolean().nullable(),
  /**
   * // extension: why the request failed or was aborted.
   *
   * Written together with `is_error: true`; a request that completed normally has neither.
   * The schema does not enforce that pairing — a consumer that wants the reason should read
   * `error`, and one that only wants a yes/no should read `is_error` — but the server always
   * writes the two consistently.
   */
  error: SpanErrorSchema.optional(),
  /**
   * // extension: the chunk range this span end replaces (D9, issue #46).
   *
   * A request whose streamed chunks will have no `agent.message` of their own — it was
   * interrupted before storing one, it streamed no text at all, or a recovering brain closes
   * it with `brain_lost` after a crash — supersedes the orphaned chunks here instead. See
   * {@link SupersedesSchema} for the range's meaning and who reads it.
   */
  supersedes: SupersedesSchema.optional(),
})

export type ModelRequestEndEvent = z.infer<typeof ModelRequestEndEventSchema>

/** {@link ModelRequestEndEvent}, deep-readonly: the shape a store returns (D9). */
export type ImmutableModelRequestEndEvent = DeepReadonly<ModelRequestEndEvent>

/** Any stored span event. */
export const SpanEventSchema = z.discriminatedUnion('type', [
  ModelRequestStartEventSchema,
  ModelRequestEndEventSchema,
])

export type SpanEvent = z.infer<typeof SpanEventSchema>
