/**
 * The provider registry: a committed snapshot of models.dev, behind a seam (epic #92, C2;
 * issue #90, #234).
 *
 * The catalogue reads it for two things: to join metadata onto the models a provider listed
 * (`name`, context window, max output, chat capability — the fields the provider's own list
 * may not carry), and to serve a provider's chat models when its own list failed or does not
 * exist (C3's `fallback`). Nothing here touches the network: the registry is
 * `models-dev.json`, a file in this package, bundled into `dist/` at build time and read from
 * there.
 *
 * ## What the snapshot carries
 *
 * `models-dev.json` is generated by `yarn workspace @openharness/server catalog:refresh`
 * (`scripts/refresh-models-dev.mjs`), which fetches https://models.dev/api.json and keeps the
 * 11 providers this server can validate a key for — the same list as
 * `VALIDATABLE_PROVIDERS` — with each model's display name, context window, output limit and
 * **list price** (epic #245, A2: input, output and the two cache rates, per million tokens, for
 * the models models.dev prices). The file records the date it was taken, so the data is only as
 * fresh as a commit.
 *
 * **It carries no chat verdict**, and that is a finding rather than an omission: models.dev
 * has no chat flag, and the fields it has are not one — `modalities.output` is `["text"]` for
 * `text-embedding-3-small` too, and `family` is a name family. So the catalogue's C2 steps 1
 * and 2 stay silent for a snapshot model and step 3's name filter decides, exactly as the
 * registry of ids alone did. `RegistryModel.chat` is still read when a
 * registry has one (a test's stub, a future snapshot that finds a real signal).
 *
 * The snapshot is keyed by **our** provider ids, not models.dev's: the generator maps
 * models.dev's `fireworks-ai`/`togetherai` onto the `fireworks`/`together` a `provider/model`
 * id carries, so nothing here has to know the difference. A provider the snapshot has no entry
 * for answers an empty list — that is a real answer, not an error: `registryFallback` then
 * serves an empty model list, and the catalog's C3 status still tells the caller why.
 */

import type { ModelCost } from '@openharness/protocol'

import modelsDevSnapshot from './models-dev.json'

/** One model the registry knows, as much of it as the snapshot carries. */
export interface RegistryModel {
  /** The raw model id, without the `provider/` prefix. */
  readonly id: string
  /** The registry's display name for it, when the registry has one. */
  readonly name?: string
  /** The context window in tokens, when the registry has one. */
  readonly contextWindow?: number
  /** The largest output in tokens, when the registry has one. */
  readonly maxOutput?: number
  /** The registry's chat verdict, when the registry classifies models at all. */
  readonly chat?: boolean
  /**
   * The model's list price in USD per million tokens, when models.dev publishes one (epic #245,
   * A2; issue #247).
   *
   * Absent — not zero, not a guessed rate — for the models nobody prices: their requests report
   * tokens and no cost, which is what "—" in a client means. A rate inside the price is `null`
   * when models.dev has none for that counter (plenty of providers publish input and output and
   * no cache rates), which is a different statement again: the counter is real and its price is
   * unknown.
   */
  readonly cost?: ModelCost
}

/**
 * Where the catalogue's metadata comes from. One method, because the two uses — joining
 * metadata onto a provider-listed model, and listing a provider's chat models on a fallback —
 * are the same read at different granularity.
 */
export interface ModelRegistry {
  /**
   * Every model the registry knows for a provider, or an empty list when it knows none.
   *
   * A read, never a fetch: an implementation must not reach the network (C2).
   */
  models(provider: string): readonly RegistryModel[]
}

/** A registry that knows nothing: what a host (or a test) gets when it wants no data at all. */
export const emptyRegistry: ModelRegistry = {
  models: () => [],
}

/** One model in the snapshot file, as the refresh script writes it. */
interface SnapshotModel {
  readonly name?: string
  readonly contextWindow?: number
  readonly maxOutput?: number
  readonly chat?: boolean
  /** The price, in the script's spelling; `cacheRead`/`cacheWrite` are its camelCase. */
  readonly cost?: SnapshotCost
}

/** One model's price in the snapshot file: USD per million tokens, cache rates optional. */
interface SnapshotCost {
  readonly input: number
  readonly output: number
  readonly cacheRead?: number
  readonly cacheWrite?: number
}

/** One provider in the snapshot file: models.dev's key for it, its name, and its models. */
interface SnapshotProvider {
  readonly key: string
  readonly name: string
  readonly models: Readonly<Record<string, SnapshotModel>>
}

/** The snapshot file's shape. `snapshot_date` and `source` are provenance, not data. */
interface Snapshot {
  readonly snapshot_date: string
  readonly source: string
  readonly providers: Readonly<Record<string, SnapshotProvider>>
}

/**
 * The snapshot, read from the bundle.
 *
 * A static import on purpose: the bundler inlines the JSON document into `dist/index.js`, so
 * the data is part of the build the same way a constant is — a deployed server cannot be
 * missing it, and reading it can never reach a disk, let alone the network (C2). The cast is
 * what keeps the 600-odd model entries out of the type checker's way: the file's own shape
 * would otherwise become a literal type here, and `Snapshot` is the four fields this module
 * reads.
 */
const SNAPSHOT = modelsDevSnapshot as unknown as Snapshot

/** The snapshot's models, per provider, built once: the file is a module-level constant. */
const MODELS_BY_PROVIDER: ReadonlyMap<string, readonly RegistryModel[]> = new Map(
  Object.entries(SNAPSHOT.providers).map(([provider, entry]) => [
    provider,
    Object.entries(entry.models).map(([id, model]) => {
      const cost = registryCost(model.cost)
      return {
        id,
        name: model.name,
        contextWindow: model.contextWindow,
        maxOutput: model.maxOutput,
        chat: model.chat,
        ...(cost === undefined ? {} : { cost }),
      }
    }),
  ]),
)

/**
 * A snapshot price as the protocol spells it: the two cache rates are `null` when models.dev
 * has none for them, which is the protocol's way of saying "a rate nobody published" — see
 * `ModelCost`. A price stays absent when the snapshot has none at all.
 */
function registryCost(cost: SnapshotCost | undefined): ModelCost | undefined {
  if (cost === undefined) {
    return undefined
  }
  return {
    input: cost.input,
    output: cost.output,
    cache_read: cost.cacheRead ?? null,
    cache_write: cost.cacheWrite ?? null,
  }
}

/** When the committed snapshot was taken, as `YYYY-MM-DD` — the age of everything above. */
export const SNAPSHOT_DATE: string = SNAPSHOT.snapshot_date

/**
 * The `ModelRegistry` over this package's committed models.dev snapshot.
 *
 * Sync and network-free: the data is in the bundle. Every field the snapshot carries is
 * filled — the name, and the two limits, which are what the provider's own list leaves `null`;
 * a provider or model it does not know answers `undefined` for the optional ones, which the
 * catalogue reads as "the registry says nothing" — the name falls back to the provider's or
 * the model id, the limits stay `null`, and the chat filter's name heuristic decides.
 */
export function createBundledRegistry(): ModelRegistry {
  return {
    models: (provider) => MODELS_BY_PROVIDER.get(provider) ?? [],
  }
}
